config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   root 'welcome#index'

   get 'welcome/index'

  # get 'articles', to: 'articles#index'
  # get 'articles/new', to: 'articles#new', as: 'new_article'
  # post 'articles', to: 'articles#create'
  # get 'articles/:id', to: 'articles#show', as: 'article'
  # get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  # patch 'articles/:id', to: 'articles#update'
  # delete 'articles/:id', to: 'articles#destroy'

  #resources :articles  # ten wpis w routes zastępuje wszystkie powyższe %>
  #resources :comments

  resources :articles do   # ten wpis zastępuje powyższe, aby każdy komantarz należał do odpowiedniego artykułu
    get 'toggle_visibility', on: :member
    resources :comments do
      resources :opinions
    end
    resources :likes, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

 validates :body, presence: true, length: { in: 5..500 }

 belongs_to :article, counter_cache: true
 belongs_to :user
 has_many :opinions, dependent: :destroy
 has_many :users, through: :opinions


 def rating_sum
   array = opinions.map do |o|
     o.opinion
   end
   array.sum
 end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

   http_basic_authenticate_with name: "admin", password: "secret", only: :destroy
   before_action :find_article
   before_action :authenticate_user!

   def create
      @comment = Comment.new(comment_params)
      @comment.article = @article
      @comment.user = current_user if current_user
      @like = Like.find_or_initialize_by(article: @article, user: current_user)

      if @comment.save
         flash[:notice] = "Your comment has been added to the article."
         redirect_to article_path(@article)
      else
         render 'articles/show'
      end
   end

   def destroy
      @comment = Comment.find(params[:id])
      return unless authorize_comment
    
      @comment.destroy
      flash[:notice] = "Your comment has been deleted."
      redirect_to article_path(@article)
   end

   def edit
      @comment = Comment.find(params[:id])
      return unless authorize_comment
   end

   def update
      @comment = Comment.find(params[:id])
      return unless authorize_comment

      if @comment.update(comment_params)
         flash[:notice] = "Your comment has been updated."
         redirect_to article_path(@article)
      else
         render 'edit'
      end
   end


   private

   def authorize_comment
      if @comment.user != current_user && !current_user&.admin?
         flash[:alert] = "You are not allowed to be here."
         redirect_to welcome_index_path
         false
      else
         true
      end
   end

   def find_article
      @article = Article.published.find(params[:article_id])
   end

   def comment_params
      params.require(:comment).permit(:body, :user)
   end

end

app/views/comments/_comment.html.erb
<p>
   <strong>Commenter:</strong>
   <%= comment.user.email %>
</p>
<p>
   <strong>Text:</strong>
   <%= simple_format(comment.body) %>
</p>
<p>
   <strong>Date:</strong>
   <%= comment.created_at %>
</p>
<p>
  <strong>Rates amount:</strong>
  <%= comment.opinions.count %>
</p>
<p>
  <strong>Rating of comment:</strong>
  <%= comment.opinions.sum(:opinion) %>
</p>

<% if comment.user == current_user || current_user&.admin? %>
  <%= link_to 'Edit', edit_article_comment_path(article_id: comment.article.id, id: comment.id) %>
  <%= link_to 'Destroy', article_comment_path(article_id: comment.article.id, id: comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>


<% if opinion = comment.opinions.where(user: current_user).first %>
  <%= link_to "Destroy opinion", article_comment_opinion_path(article_id: @article.id, comment_id: comment.id, id: opinion.id), method: :delete %>
<% else %>
  <%= form_for [@article, comment, @opinion], url: article_comment_opinions_path(@article, comment, @opinion) do |f| %>
    <%= f.label :opinion %>
    <%= f.collection_radio_buttons :opinion, [[1, 'Plus'], [-1, 'Minus']], :first, :last %>
    <%= f.submit %>
  <% end %>
<% end %>
<br>
<br>

app/views/comments/_form.html.erb
<%= render 'common/errors', model: @comment %>

<%= form_for [@article, @comment], url: article_comments_path(@article, @comment) do |f| %>

   <div class="form-group">
      <%= f.label :body, 'Content' %>  <br>
      <%= f.text_area :body, class: 'form-control' %>
   </div>
   <div class="form-group">
      <%= f.submit class: 'btn btn-dark' %>
   </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>