config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   root 'welcome#index'

   get 'welcome/index'

  # get 'articles', to: 'articles#index'
  # get 'articles/new', to: 'articles#new', as: 'new_article'
  # post 'articles', to: 'articles#create'
  # get 'articles/:id', to: 'articles#show', as: 'article'
  # get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  # patch 'articles/:id', to: 'articles#update'
  # delete 'articles/:id', to: 'articles#destroy'

  #resources :articles  # ten wpis w routes zastępuje wszystkie powyższe %>
  #resources :comments

  resources :articles do   # ten wpis zastępuje powyższe, aby każdy komantarz należał do odpowiedniego artykułu
    get 'toggle_visibility', on: :member
    resources :comments do
      resources :opinions
    end
    resources :likes, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord

   validates :title, presence: true, length: { minimum: 5 }

   has_many :comments, dependent: :destroy
   belongs_to :user
   has_many :likes
   has_many :users, through: :likes

   scope :published, -> { where(published: true) }
   scope :most_commented, -> { order(comments_count: :DESC).first }


   mount_uploader :cover, CoverUploader

   def tags=(value)
      value = sanitize_tags(value) if value.is_a?(String)
      super(value)
   end


   def css_class
     if published?
       'normal'
     else
       'unpublished'
     end
   end

   private

   def sanitize_tags(text)
      text.downcase.split.uniq
   end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

   http_basic_authenticate_with name: "admin", password: "secret", except: [:index, :show]
   before_action :find_article, only: [:show, :edit, :update, :destroy, :toggle_visibility]
   before_action :authenticate_user!, except: [:show, :index]
   before_action :authorize_article, only: [:edit, :update, :destroy]

   def index
     if current_user&.admin?
       @articles = Article.all
     else
       @articles = Article.published
     end
     @most_commented = @articles.most_commented
     @articles = @articles.includes(:user).order(id: :desc).page(params[:page]).per(3)
     @articles = @articles.where("? = any(tags)", params[:q]) if params[:q].present?
      # lub @articles = @articles.select { |a| a.tags.include? params[:q] } if params[:q].present?
   end

   def new
      @article = Article.new
   end

   def create
      @article = Article.new(article_params)
      @article.user = current_user if current_user
      if @article.save
         flash[:notice] = "Your article has beed succesfully saved in our data base."
         redirect_to article_path(@article)
      else
         render 'new'
      end
   end

   def show
      @comment = Comment.new
      @like = Like.find_or_initialize_by(article: @article, user: current_user)
      @opinion = Opinion.new

      respond_to do |format|
        format.html do
          @article.increment!(:views_count)
          render
        end
        format.json do
          render json: {
            id: @article.id,
            title: @article.title,
            text: @article.text,
            views_count: @article.views_count,
            likes_count: @article.likes.count,
            comments_count: @article.comments.count
          }
        end
      end
   end

   def edit
   end

   def update
      if @article.update(article_params)
         flash[:notice] = "Your article has been succesfully updated in our data base."
         redirect_to article_path(@article)
      else
         render 'edit'
      end
   end

   def destroy
      @article.destroy
      flash[:notice] = "Your article has been succesfully deleted from our data base."
      redirect_to welcome_index_path
   end

   def toggle_visibility
     return redirect_to articles_path, alert: 'Not found' unless current_user&.admin?
     @article.toggle!(:published)
     flash[:notice] = 'Your article\'s visibility has benn changed'
     redirect_to articles_path, notice: 'Your article\'s visibility has benn changed'
   end


   private

   def authorize_article
      if @article.user != current_user && !current_user&.admin?
         flash[:alert] = "You are not allowed to be here."
         redirect_to welcome_index_path
         false
      else
         true
      end
   end

   def article_params
      params.require(:article).permit(:title, :text, :tags, :user, :type, :cover)
   end

   def find_article
      @article =  if current_user&.admin?
                    Article.find(params[:id])
                  else
                    Article.published.find(params[:id])
                  end
   end
end

app/views/articles/_form.html.erb
<%= render 'common/errors', model: @article %>

<%= form_for @article.becomes(Article) do |f| %>
   <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
   </div>
   <div class="form-group">
      <%= f.label :text %>  <br>
      <%= f.text_area :text, class: 'form-control' %>
   </div>
   <div class="form-group">
      <%= f.label :tags %>  <br>
      <%= f.text_field :tags, class: 'form-control' %>
   </div>
   <div class="form-group">
      <p><%= f.label :cover %>  <br>
        <%= image_tag(@article.cover_url) if @article.cover? %>
        <%= f.file_field :cover %>
        <%= f.hidden_field :cover_cache %></p>
      <p><label>
        <%= f.check_box :remove_cover %>
        Remove avatar
      </label></p>
   </div>
   <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
   </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>My articles</h1>
<br>
<% if @articles.any? %>
<h3>Most commented article is <%= link_to @most_commented.title, article_path(@most_commented) %> <h3>
<% end %>


<table class="table">
   <thead>
      <tr>
         <th>Title</th>
         <th>Author</th>
         <th>Text</th>
         <th>Likes</th>
         <th>Comments amount</th>
         <th></th>
         <th></th>
         <th></th>
         <th></th>
      </tr>
   </thead>
   <tbody>
      <% @articles.each do |article| %>
         <tr class="<%= article.css_class %>">
            <td><%= article.title %></td>
            <td><%= article.user.email %></td>
            <td><%= article.text %></td>
            <td><%= article.likes.size %></td>
            <td><%= article.comments.count %></td>
            <td><%= link_to 'Summary', article_path(article), class: 'btn btn-info summary', id: "summary-#{article.id}"%> </td>
            <td><%= link_to 'Show', article_path(article) %></td>
            <td><%= link_to 'Edit', edit_article_path(article) if article.user == current_user || current_user&.admin? %></td>
            <td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } if article.user == current_user || current_user&.admin? %></td>
         </tr>
      <% end %>
   </tbody>
</table>
<br>
Articles: <%= @articles.total_count %>
<br>
<br>
<%= form_tag articles_path, method: :get do %>
   <div class="input-group">
      <%= text_field_tag :q, params[:q], class: "form-control" %>
      <span class="input-group-btn">
         <%= submit_tag "Search", class: "btn btn-default" %>
      </span>
   </div>
<% end %>
<br>
<%= link_to 'New Article', new_article_path %>
<br>
<%= paginate @articles, theme: 'twitter-bootstrap-4' %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1>My Article</h1>
<p>
<% if sponsored_article?(@article) %>
  <h4> Artykuł sponsorowany przez firmę <%= @article.company.name %></h4>
<% end %>
</p>
<br>
<br>
<p>
   <strong>Title:</strong>
   <%= @article.title %>
</p>
<p>
    <%= image_tag(@article.cover.url, alt: 'Image') if @article.cover? %></p>
</p>
<p>
   <strong>Text:</strong>
   <%= @article.text %>
</p>
<p>
   <strong>Author:</strong>
   <%= @article.user.email %>
</p>
<p>
   <strong>Tags:</strong>
   <% @article.tags.each do |tag| %>
      <%= link_to tag, articles_path(q: tag), class: "badge badge-pill badge-dark" %>
   <% end %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>

<br>
<br>

<%= pluralize(@article.likes.count, 'person') %> liked this article
<% if @like.persisted? %>
  <i class="fa fa-thumbs-down"></i>
  <%= link_to 'Unlike', article_like_path(@article, @like), method: :delete %>
<% else %>
  <i class="fa fa-thumbs-up"></i>
  <%= link_to 'Like', article_likes_path(@article), method: :post %>
<% end %>

<br>
<br>

<% if sponsored_article?(@article) %>
  <p>Komentarze zablokowane</p>
<% else %>
  <h1>Comments</h1>
  <%#= render @article.comments.includes(:user) %>
  <% @article.comments.includes(:user).each do |comment| %>
    <% if comment.opinions.sum(:opinion) < -2 %>
      <span style="background-color: Blue"> Komentarz zablokowany </span>
      <br>
      <br>
    <% else %>
      <%= render comment %>
    <% end %>
  <% end %>
<% end %>


<h3> Add a comment </h3>
<%= render 'comments/form' %>

<br>
<br>

<%= link_to 'Back', articles_path %>

<% if current_user&.admin? %>
  <%= link_to @article.published? ? "Unpublish" : "Publish", toggle_visibility_article_path(@article) %>
<% end %>